// Generated by CoffeeScript 1.6.3
(function() {
  var fs, _;

  fs = require('node-fs');

  _ = require('lodash');

  exports.post = function(data, room) {
    if (!exports[room]) {
      exports.newRoom(room);
    }
    data = JSON.parse(data);
    data.createdAt = data.modifiedAt = Date('UTC');
    console.log(data);
    exports[room].results.push(data);
    fs.writeFile('./chatStorage', JSON.stringify(exports));
    return console.log(exports[room].results);
  };

  exports.newRoom = function(room) {
    return exports[room] = {
      results: []
    };
  };

  exports.loadTweets = function() {
    return fs.readFile('./chatStorage', function(err, data) {
      var parsedStorage;
      parsedStorage = JSON.parse(data);
      return _.extend(exports, parsedStorage);
    });
  };

}).call(this);

/*
//@ sourceMappingURL=rooms.map
*/
